env:
  es6: true
  node: true
  jasmine: true
extends: 'eslint:recommended'
rules:
  no-console:
    - error
    - allow:
      - warn
      - error
      - info
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - never
